formatter: "markdown table"

version: ">= 0.16.0"

header-from: main.tf

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Architecture

  This Terraform configuration deploys a multi-region GKE platform with:
  - Multiple GKE clusters with Fleet management
  - Multi-cluster services and ingress
  - Cloud NAT for outbound connectivity
  - Load balancer configuration

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
